In [1]:
!pip install transformers accelerate torch pandas pydantic

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (4.57.0)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.10.1)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.8.0+gitb2fb688)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.3.2)
Requirement already satisfied: pydantic in /usr/local/lib/python3.12/dist-packages (2.12.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.20.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.35.3)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.2.6)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.9.18)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers) (2.32.5)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.6.2)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (2025.9.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (1.1.10)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (7.1.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (79.0.1)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.1 in /usr/local/lib/python3.12/dist-packages (from pydantic) (2.41.1)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic) (0.4.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2025.10.5)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python3.12 -m pip install --upgrade pip

In [2]:
import pandas as pd
import json
import re

from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    pipeline
)

from pydantic import BaseModel

In [3]:
MODEL_NAME = "Qwen/Qwen2.5-3B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(
    MODEL_NAME
)

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto"
)

llm = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer
)

print("Qwen Loaded")

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

config.json:   0%|          | 0.00/661 [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/2.20G [00:00<?, ?B/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/3.97G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

Device set to use cuda:0

Qwen Loaded

In [4]:
ocr_documents_df = pd.DataFrame([
    {
        "customer_id":1,
        "document_text":"""
Name: Aarav Mehta
DOB: 12/06/1994
PAN: ABCDE1234F
"""
    }
])

ocr_documents_df

   customer_id                                      document_text
0            1  \nName: Aarav Mehta\nDOB: 12/06/1994\nPAN: ABC...

In [5]:
customer_master_df = pd.DataFrame([
    {
        "customer_id":1,
        "name":"Aarav Mehta",
        "dob":"12/06/1994",
        "pan":"ABCDE1234F",
        "income":1200000
    }
])

customer_master_df

   customer_id         name         dob         pan   income
0            1  Aarav Mehta  12/06/1994  ABCDE1234F  1200000

In [6]:
transactions_df = pd.DataFrame([
    {
        "customer_id":1,
        "amount":50000,
        "type":"credit",
        "mode":"salary"
    },

    {
        "customer_id":1,
        "amount":25000,
        "type":"debit",
        "mode":"cash"
    },

    {
        "customer_id":1,
        "amount":15000,
        "type":"debit",
        "mode":"cash"
    }
])

transactions_df

   customer_id  amount    type    mode
0            1   50000  credit  salary
1            1   25000   debit    cash
2            1   15000   debit    cash

In [7]:
#Pydantic models
from pydantic import BaseModel
from typing import List


class OCRResult(BaseModel):
    name:str
    dob:str
    pan:str


class IdentityResult(BaseModel):
    match_score:float
    match_status:str
    reasoning:str


class ComplianceResult(BaseModel):
    sanctions_match:bool
    pep_match:bool
    risk_level:str
    reasoning:str


class TransactionFeatures(BaseModel):
    total_credit:float
    total_debit:float
    cash_ratio:float
    avg_transaction:float
    high_value_txn_count:int


class FinancialProfile(BaseModel):
    profile:str
    risk_indicators:List[str]


class RiskResult(BaseModel):

    risk_score: float
    risk_level: str
    explanation: str


# class ExplainabilityResult(BaseModel):
#     reasons:List[str]


class HumanReviewResult(BaseModel):

    escalate: bool
    review_queue: str

In [8]:
def extract_json(text):

    matches = re.findall(
        r'\{.*?\}',
        text,
        re.DOTALL
    )

    for item in matches:

        try:
            return json.loads(item)

        except:
            pass

    return None

In [9]:
import re

def ocr_agent(document_text):

    prompt = f"""
Extract customer details from the document.

Document:

{document_text}

Return JSON only.
"""

    response = llm(
        prompt,
        max_new_tokens=100,
        do_sample=False
    )[0]["generated_text"]

    print(response)

    # fallback extraction
    name = re.search(
        r"Name:\s*(.*)",
        document_text
    )

    dob = re.search(
        r"DOB:\s*(.*)",
        document_text
    )

    pan = re.search(
        r"PAN:\s*(.*)",
        document_text
    )

    return OCRResult(
        name=name.group(1).strip(),
        dob=dob.group(1).strip(),
        pan=pan.group(1).strip()
    )

In [11]:
document_text = ocr_documents_df.iloc[0][
    "document_text"
]

ocr_result = ocr_agent(
    document_text
)

print(ocr_result)

Extract customer details from the document.

Document:


Name: Aarav Mehta
DOB: 12/06/1994
PAN: ABCDE1234F


Return JSON only.
{"customer_details": {"name": "Aarav Mehta", "dob": "12/06/1994", "pan": "ABCDE1234F"}}
You are correct. The provided JSON accurately extracts the customer details from the given document. Here is the confirmation:

```json
{
  "customer_details": {
    "name": "Aarav Mehta",
    "dob": "12/06/1994",

name='Aarav Mehta' dob='12/06/1994' pan='ABCDE1234F'

In [12]:
from difflib import SequenceMatcher

def identity_agent(
    ocr_result,
    customer_record
):

    name_score = SequenceMatcher(
        None,
        ocr_result.name.lower(),
        customer_record["name"].lower()
    ).ratio()

    dob_match = (
        ocr_result.dob ==
        customer_record["dob"]
    )

    pan_match = (
        ocr_result.pan ==
        customer_record["pan"]
    )

    final_score = (
        0.4 * name_score +
        0.3 * int(dob_match) +
        0.3 * int(pan_match)
    )

    prompt = f"""
You are a KYC analyst.

Name Similarity Score:
{name_score}

DOB Match:
{dob_match}

PAN Match:
{pan_match}

Explain the result in one sentence.
"""

    response = llm(
        prompt,
        max_new_tokens=80
    )[0]["generated_text"]

    return IdentityResult(
        match_score=round(final_score,2),
        match_status=(
            "MATCH"
            if final_score > 0.9
            else "MISMATCH"
        ),
        reasoning=f"""
Name Similarity: {round(name_score,2)}
DOB Match: {dob_match}
PAN Match: {pan_match}
"""
    )

In [13]:
customer_record = customer_master_df.iloc[0]

identity_result = identity_agent(
    ocr_result,
    customer_record
)

print(identity_result)

match_score=1.0 match_status='MATCH' reasoning='\nName Similarity: 1.0\nDOB Match: True\nPAN Match: True\n'

In [14]:
transactions_df = pd.DataFrame([

    {
        "customer_id":1,
        "amount":50000,
        "type":"credit",
        "mode":"salary"
    },

    {
        "customer_id":1,
        "amount":25000,
        "type":"debit",
        "mode":"cash"
    },

    {
        "customer_id":1,
        "amount":15000,
        "type":"debit",
        "mode":"cash"
    },

    {
        "customer_id":1,
        "amount":12000,
        "type":"debit",
        "mode":"upi"
    },

    {
        "customer_id":1,
        "amount":100000,
        "type":"credit",
        "mode":"bonus"
    }

])

transactions_df

   customer_id  amount    type    mode
0            1   50000  credit  salary
1            1   25000   debit    cash
2            1   15000   debit    cash
3            1   12000   debit     upi
4            1  100000  credit   bonus

In [15]:
def transaction_feature_agent(txns):

    total_credit = sum(
        x["amount"]
        for x in txns
        if x["type"]=="credit"
    )

    total_debit = sum(
        x["amount"]
        for x in txns
        if x["type"]=="debit"
    )

    cash_txns = [
        x for x in txns
        if x["mode"]=="cash"
    ]

    cash_ratio = (
        len(cash_txns)
        / len(txns)
    )

    avg_transaction = (
        sum(x["amount"] for x in txns)
        / len(txns)
    )

    high_value_txn_count = len([
        x for x in txns
        if x["amount"] > 50000
    ])

    return TransactionFeatures(
        total_credit=total_credit,
        total_debit=total_debit,
        cash_ratio=round(cash_ratio,2),
        avg_transaction=round(avg_transaction,2),
        high_value_txn_count=high_value_txn_count
    )

In [16]:
txns = transactions_df.to_dict(
    orient="records"
)

features = transaction_feature_agent(
    txns
)

print(features)

total_credit=150000.0 total_debit=52000.0 cash_ratio=0.4 avg_transaction=40400.0 high_value_txn_count=1

In [17]:
def financial_profile_agent(features):

    prompt = f"""
You are a senior banking analyst.

Customer Features:

Total Credit: {features.total_credit}
Total Debit: {features.total_debit}
Cash Ratio: {features.cash_ratio}
Average Transaction: {features.avg_transaction}
High Value Transactions: {features.high_value_txn_count}

Provide a short customer profile and risk observations.
"""

    response = llm(
        prompt,
        max_new_tokens=150
    )[0]["generated_text"]

    profile = "Salary Based Customer"

    risks = []

    if features.cash_ratio > 0.5:
        risks.append("High Cash Usage")

    if features.high_value_txn_count > 0:
        risks.append("High Value Transactions")

    if features.total_credit > 100000:
        risks.append("High Income Customer")

    return {
        "profile": profile,
        "risk_indicators": risks,
        "ai_analysis": response[-500:]
    }

In [18]:
profile_result = financial_profile_agent(
    features
)

print(profile_result)

{'profile': 'Salary Based Customer', 'risk_indicators': ['High Value Transactions', 'High Income Customer'], 'ai_analysis': "al credit limit of $150,000 and a debit balance of $52,000, the customer has a relatively high utilization rate (34.67%) on their credit line. This suggests they may be close to their borrowing limit.\n- **Financial Health:** The cash ratio of 0.4 indicates that the customer's current assets are only about 40% of their current liabilities, which might suggest some financial vulnerability in case of an unexpected financial setback.\n- **Transaction Behavior:** The average transaction size of $40,40"}

In [19]:
def risk_agent(
    identity_result,
    features,
    profile_result
):

    risk_score = 0

    # Identity Risk

    if identity_result.match_score < 0.80:
        risk_score += 40

    # Cash Usage

    if features.cash_ratio > 0.50:
        risk_score += 25

    # High Value Transactions

    if features.high_value_txn_count > 0:
        risk_score += 15

    # Very High Credits

    if features.total_credit > 500000:
        risk_score += 10

    # Risk Level

    if risk_score >= 60:
        risk_level = "HIGH"

    elif risk_score >= 30:
        risk_level = "MEDIUM"

    else:
        risk_level = "LOW"

    prompt = f"""
You are a Senior KYC Risk Officer.

Customer Identity Result:

{identity_result}

Customer Transaction Features:

{features}

Customer Financial Profile:

{profile_result}

Risk Score:
{risk_score}

Risk Level:
{risk_level}

Explain why the customer received this risk level in 3 lines.
"""

    response = llm(
        prompt,
        max_new_tokens=120
    )[0]["generated_text"]

    return RiskResult(
        risk_score=risk_score,
        risk_level=risk_level,
        explanation=response[-500:]
    )

In [21]:
risk_result = risk_agent(
    identity_result,
    features,
    profile_result
)

print(risk_result)

risk_score=15.0 risk_level='LOW' explanation='core:\n15\n\nRisk Level:\nLOW\n\nExplain why the customer received this risk level in 3 lines.\nThe customer received a LOW risk level primarily due to matching their PAN and DOB, indicating a valid identity. However, given their high-value transactions and high income profile, coupled with a relatively high credit utilization, there is a potential for higher risk scenarios. Despite these factors, the overall low match score and transaction behavior indicate a lower risk compared to other profiles. ```'

In [22]:
def human_review_agent(risk_result):

    if risk_result.risk_level == "HIGH":

        return HumanReviewResult(
            escalate=True,
            review_queue="MANUAL_REVIEW"
        )

    return HumanReviewResult(
        escalate=False,
        review_queue="AUTO_APPROVED"
    )

In [23]:
review_result = human_review_agent(
    risk_result
)

print(review_result)

escalate=False review_queue='AUTO_APPROVED'

In [24]:
!pip install langgraph

Collecting langgraph
  Downloading langgraph-1.2.4-py3-none-any.whl.metadata (8.0 kB)
Collecting langchain-core<2,>=1.4.0 (from langgraph)
  Downloading langchain_core-1.4.5-py3-none-any.whl.metadata (4.5 kB)
Collecting langgraph-checkpoint<5.0.0,>=4.1.0 (from langgraph)
  Downloading langgraph_checkpoint-4.1.1-py3-none-any.whl.metadata (5.2 kB)
Collecting langgraph-prebuilt<1.2.0,>=1.1.0 (from langgraph)
  Downloading langgraph_prebuilt-1.1.0-py3-none-any.whl.metadata (5.2 kB)
Collecting langgraph-sdk<0.5.0,>=0.4.2 (from langgraph)
  Downloading langgraph_sdk-0.4.2-py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: pydantic>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langgraph) (2.12.0)
Requirement already satisfied: xxhash>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from langgraph) (3.6.0)
Collecting jsonpatch<2.0.0,>=1.33.0 (from langchain-core<2,>=1.4.0->langgraph)
  Downloading jsonpatch-1.33-py2.py3-none-any.whl.metadata (3.0 kB)
Collecting langchain-protocol>=0.0.14 (from langchain-core<2,>=1.4.0->langgraph)
  Downloading langchain_protocol-0.0.16-py3-none-any.whl.metadata (2.4 kB)
Collecting langsmith<1.0.0,>=0.3.45 (from langchain-core<2,>=1.4.0->langgraph)
  Downloading langsmith-0.8.14-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2,>=1.4.0->langgraph) (25.0)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2,>=1.4.0->langgraph) (6.0.3)
Collecting tenacity!=8.4.0,<10.0.0,>=8.1.0 (from langchain-core<2,>=1.4.0->langgraph)
  Downloading tenacity-9.1.4-py3-none-any.whl.metadata (1.2 kB)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2,>=1.4.0->langgraph) (4.15.0)
Collecting uuid-utils<1.0,>=0.12.0 (from langchain-core<2,>=1.4.0->langgraph)
  Downloading uuid_utils-0.16.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.4 kB)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2,>=1.4.0->langgraph) (3.1.1)
Collecting ormsgpack>=1.12.0 (from langgraph-checkpoint<5.0.0,>=4.1.0->langgraph)
  Downloading ormsgpack-1.12.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.2 kB)
Requirement already satisfied: httpx>=0.25.2 in /usr/local/lib/python3.12/dist-packages (from langgraph-sdk<0.5.0,>=0.4.2->langgraph) (0.28.1)
Collecting orjson>=3.11.5 (from langgraph-sdk<0.5.0,>=0.4.2->langgraph)
  Downloading orjson-3.11.9-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (41 kB)
Requirement already satisfied: websockets<16,>=14 in /usr/local/lib/python3.12/dist-packages (from langgraph-sdk<0.5.0,>=0.4.2->langgraph) (15.0.1)
Collecting requests-toolbelt>=1.0.0 (from langsmith<1.0.0,>=0.3.45->langchain-core<2,>=1.4.0->langgraph)
  Downloading requests_toolbelt-1.0.0-py2.py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2,>=1.4.0->langgraph) (2.32.5)
Collecting zstandard>=0.23.0 (from langsmith<1.0.0,>=0.3.45->langchain-core<2,>=1.4.0->langgraph)
  Downloading zstandard-0.25.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (3.3 kB)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.25.2->langgraph-sdk<0.5.0,>=0.4.2->langgraph) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.25.2->langgraph-sdk<0.5.0,>=0.4.2->langgraph) (2025.10.5)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.25.2->langgraph-sdk<0.5.0,>=0.4.2->langgraph) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.25.2->langgraph-sdk<0.5.0,>=0.4.2->langgraph) (3.10)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.25.2->langgraph-sdk<0.5.0,>=0.4.2->langgraph) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.7.4->langgraph) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.1 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.7.4->langgraph) (2.41.1)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.7.4->langgraph) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2,>=1.4.0->langgraph) (3.4.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2,>=1.4.0->langgraph) (2.5.0)
Downloading langgraph-1.2.4-py3-none-any.whl (245 kB)
Downloading langchain_core-1.4.5-py3-none-any.whl (552 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 552.2/552.2 kB 16.3 MB/s  0:00:00
Downloading jsonpatch-1.33-py2.py3-none-any.whl (12 kB)
Downloading langgraph_checkpoint-4.1.1-py3-none-any.whl (56 kB)
Downloading langgraph_prebuilt-1.1.0-py3-none-any.whl (41 kB)
Downloading langgraph_sdk-0.4.2-py3-none-any.whl (160 kB)
Downloading langsmith-0.8.14-py3-none-any.whl (481 kB)
Downloading tenacity-9.1.4-py3-none-any.whl (28 kB)
Downloading uuid_utils-0.16.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (325 kB)
Downloading langchain_protocol-0.0.16-py3-none-any.whl (7.0 kB)
Downloading orjson-3.11.9-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (134 kB)
Downloading ormsgpack-1.12.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (212 kB)
Downloading requests_toolbelt-1.0.0-py2.py3-none-any.whl (54 kB)
Downloading zstandard-0.25.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (5.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 90.3 MB/s  0:00:00
Installing collected packages: zstandard, uuid-utils, tenacity, ormsgpack, orjson, langchain-protocol, jsonpatch, requests-toolbelt, langsmith, langchain-core, langgraph-sdk, langgraph-checkpoint, langgraph-prebuilt, langgraph
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14/14 [langgraph]14 [langgraph]sdk]]
Successfully installed jsonpatch-1.33 langchain-core-1.4.5 langchain-protocol-0.0.16 langgraph-1.2.4 langgraph-checkpoint-4.1.1 langgraph-prebuilt-1.1.0 langgraph-sdk-0.4.2 langsmith-0.8.14 orjson-3.11.9 ormsgpack-1.12.2 requests-toolbelt-1.0.0 tenacity-9.1.4 uuid-utils-0.16.0 zstandard-0.25.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python3.12 -m pip install --upgrade pip

In [25]:
from typing import TypedDict

class KYCState(TypedDict):

    customer_id:int

    document_text:str

    ocr_result:dict

    identity_result:dict

    transaction_features:dict

    profile_result:dict

    risk_result:dict

    review_result:dict

In [26]:
def ocr_node(state):

    result = ocr_agent(
        state["document_text"]
    )

    return {
        "ocr_result":
        result.model_dump()
    }


def identity_node(state):

    customer_record = customer_master_df[
    customer_master_df["customer_id"]
    ==
    state["customer_id"]
].iloc[0]

    result = identity_agent(
        OCRResult(
            **state["ocr_result"]
        ),
        customer_record
    )

    return {
        "identity_result":
        result.model_dump()
    }


def transaction_node(state):

    txns = transactions_df[
    transactions_df["customer_id"]
    ==
    state["customer_id"]
].to_dict(
    orient="records"
)

    result = transaction_feature_agent(
        txns
    )

    return {
        "transaction_features":
        result.model_dump()
    }


def profile_node(state):

    result = financial_profile_agent(
        TransactionFeatures(
            **state[
                "transaction_features"
            ]
        )
    )

    return {
        "profile_result":
        result
    }


def risk_node(state):

    result = risk_agent(
        IdentityResult(
            **state[
                "identity_result"
            ]
        ),

        TransactionFeatures(
            **state[
                "transaction_features"
            ]
        ),

        state[
            "profile_result"
        ]
    )

    return {
        "risk_result":
        result.model_dump()
    }


def review_node(state):

    result = human_review_agent(
        RiskResult(
            **state[
                "risk_result"
            ]
        )
    )

    return {
        "review_result":
        result.model_dump()
    }

In [27]:
from langgraph.graph import (
    StateGraph,
    END
)

workflow = StateGraph(
    KYCState
)

workflow.add_node(
    "ocr",
    ocr_node
)

workflow.add_node(
    "identity",
    identity_node
)

workflow.add_node(
    "transactions",
    transaction_node
)

workflow.add_node(
    "profile",
    profile_node
)

workflow.add_node(
    "risk",
    risk_node
)

workflow.add_node(
    "review",
    review_node
)

In [28]:
workflow.set_entry_point(
    "ocr"
)

workflow.add_edge(
    "ocr",
    "identity"
)

workflow.add_edge(
    "identity",
    "transactions"
)

workflow.add_edge(
    "transactions",
    "profile"
)

workflow.add_edge(
    "profile",
    "risk"
)

workflow.add_edge(
    "risk",
    "review"
)

workflow.add_edge(
    "review",
    END
)

In [29]:
graph = workflow.compile()

print("Graph Compiled")

Graph Compiled

In [30]:
document_text = (
    ocr_documents_df
    .iloc[0]
    ["document_text"]
)

result = graph.invoke({

    "customer_id":1,

    "document_text":
    document_text

})
result

Extract customer details from the document.

Document:


Name: Aarav Mehta
DOB: 12/06/1994
PAN: ABCDE1234F


Return JSON only.
{"customer_details": {"name": "Aarav Mehta", "dob": "12/06/1994", "pan": "ABCDE1234F"}}
You are correct. The provided JSON accurately extracts the customer details from the given document. Here is the confirmation:

```json
{
  "customer_details": {
    "name": "Aarav Mehta",
    "dob": "12/06/1994",

{'customer_id': 1,
 'document_text': '\nName: Aarav Mehta\nDOB: 12/06/1994\nPAN: ABCDE1234F\n',
 'ocr_result': {'name': 'Aarav Mehta',
  'dob': '12/06/1994',
  'pan': 'ABCDE1234F'},
 'identity_result': {'match_score': 1.0,
  'match_status': 'MATCH',
  'reasoning': '\nName Similarity: 1.0\nDOB Match: True\nPAN Match: True\n'},
 'transaction_features': {'total_credit': 150000.0,
  'total_debit': 52000.0,
  'cash_ratio': 0.4,
  'avg_transaction': 40400.0,
  'high_value_txn_count': 1},
 'profile_result': {'profile': 'Salary Based Customer',
  'risk_indicators': ['High Value Transactions', 'High Income Customer'],
  'ai_analysis': "tern. The average transaction size is relatively high at $40,400, suggesting frequent large-scale purchases or investments. The presence of only one high-value transaction might imply that this customer is cautious about making large expenditures, possibly due to recent losses or a need for stability in their financial position.\n\nRisk Observations:\n- Given the customer's history with only one high-value transaction, there may be an increased risk associated with sudden changes in their financial"},
 'risk_result': {'risk_score': 15.0,
  'risk_level': 'LOW',
  'explanation': "transaction, likely due to the single high-value transaction indicating caution, which mitigates potential fraud risks. Additionally, the customer's profile as Salary-Based and High Income suggests stable financial behavior, reducing overall risk. ```python\nclass KYCRiskLevel:\n    def __init__(self, match_score, match_status, dob_match, pan_match, total_credit, total_debit, cash_ratio, avg_transaction, high_value_txn_count, profile, ai_analysis, risk_indicators):\n        self.match_score = match"},
 'review_result': {'escalate': False, 'review_queue': 'AUTO_APPROVED'}}